### ISSUE TITLE
.dat file

### ISSUE THREAD

**Issue by jayp84847** [HongwenZhang/JVCR-3Dlandmark#10]
Yet I am working on project where I am using 68 face landmarks in my project. But its not 3d and more stable. So I am trying to make it more stable or finding new dataset. Can you tell me how can I make ".dat" file from this 3d dataset. Or can you share me .dat file for this dataset.

**Comment by HongwenZhang** [comment]
Hi, what's the meaning of '.dat' file? Is it the file used in the dlib C++ Library?

**Comment by jayp84847** [comment]
I am using dlib 68_face_landmarks.dat file. Its dlib shape predictor
landmarks file.

Link of dlib face landmark file :
http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2

Dlib other files : http://dlib.net/files/

**Comment by HongwenZhang** [comment]
JVCR is currently based on Python and has not been packaged as a Library, so there is not such a .dat file for the algorithm and data.

**Comment by jayp84847** [comment]
Can you guide me how can I convert and use it as .dat module in my project.
Like its also seems like dlib 68 face landmarks.

**Comment by HongwenZhang** [comment]
Sorry, I am not familiar with dlib and do not know how to package it as a .dat file.
